feat: implement SignUp UI (#9)
swift-in-gangnam/soil pull request #16
Opened 2021-11-17 09:46 UTC by dudtjs1021ej

## Linked Issue

close #9

## 설명

- StoryBoard로 SignUp UI를 구성하였습니다.
- View/Auth/CustomPasswordTextField, CustomTextField, Auth.storyboard 를 만들었습니다.
- Controller/Auth/EmailConfirmController, EmailInputController, NameInputController, NickNameInputController, PasswordInputController, ProfileInputController, SignInController, LoginHomeController, SignUpCompletedController 만들었습니다.
- Lottie애니메이션을 적용했습니다.

## 변경 사항
- View/Auth/CustomPasswordTextField, CustomTextField, Auth.storyboard 추가
- Controller/Auth/EmailConfirmController, EmailInputController, NameInputController, NickNameInputController, PasswordInputController, ProfileInputController, SignInController, LoginHomeController, SignUpCompletedController 추가
- Supporting/Lottie/email-sent.json, task-completed.json 추가
- Supporting/Assets/ProfileButton.png 추가
- Controller/Profile/TabBarController의 checkIfUserIsLoggedIn() 수정

## 참고 사항

---

## Pull Request의 유형은 무엇인가요?

- [x] New Feature
- [ ] Bug Fix
- [ ] Refactoring
- [ ] Docs
- [ ] Other

## 체크리스트

- [x] Merge하는 브랜치가 올바른가?
- [x] 코딩컨벤션을 준수하는가?
- [x] PR과 관련없는 변경사항이 없는가?
- [x] 내 코드에 대한 자기 검토가 되었는가?

2021-11-17 10:05 UTC, Chuncheonian requested changes
많은 UI 하시느라 고생하셨어요! 리뷰한 것 고쳐주시면 감사하겠습니다!
또, 들여쓰기 4칸으로 되어있는데 2칸으로 변경해주세요!

2021-11-17 10:05 UTC, Chuncheonian commented on Soil/Controller/Auth/SignUpCompleteController.swift
> +      // lottie 애니메이션뷰 설정
ios에서 주석은 // 보다 /// 로 많이 쓰더라고요. 수정부탁드립니다.

2021-11-17 10:05 UTC, Chuncheonian commented on Soil/Controller/Auth/SignUpCompleteController.swift
> +    animationView.frame = CGRect(x: x, y: 180, width: 400, height: 400)
로티 애니메이션 정가운데 위치 부탁드립니다.

2021-11-17 10:05 UTC, Chuncheonian commented on Soil/View/Auth/CustomPasswordTextField.swift
> +import Foundation
Foundation 삭제 부탁드립니다.

2021-11-17 10:08 UTC, dudtjs1021ej commented on Soil/View/Auth/CustomPasswordTextField.swift
> +import Foundation
넵~! 말씀하신 것 다 수정하겠습니다!

2021-11-17 10:09 UTC, Chuncheonian commented
또 iOS14에서 네비게이션바가 이런식으로 뜹니다!

<img alt="스크린샷 2021-11-17 오후 6 54 47" src="https://user-images.githubusercontent.com/29334434/142178249-1475269d-e40f-4992-aa3b-2da218fc551f.png" width="40%" >

2021-11-17 11:50 UTC, z3rosmith commented on Soil/Controller/Auth/SignUpCompleteController.swift
> +      // lottie 애니메이션뷰 설정
저는 ///주석은 함수나 클래스의 정의 에서 문서화 시킬때만 사용하는걸로 알고있습니다!

2021-11-17 12:00 UTC, z3rosmith commented on Soil/Controller/Auth/SignUpCompleteController.swift
> +      // lottie 애니메이션뷰 설정
따라서 이 주석의 경우에는 수정 안하셔도 됩니다. ///로 바꾸면 오히려 SwiftLint에서 워닝 띄울거에요

2021-11-17 12:01 UTC, Chuncheonian commented on Soil/Controller/Auth/SignUpCompleteController.swift
> +      // lottie 애니메이션뷰 설정
아하 감사합니다~

2021-11-18 06:08 UTC, Chuncheonian approved these changes
고생하셨습니다!

2021-11-18 06:51 UTC, z3rosmith approved these changes
수고하셨습니다 !!

2021-11-18 07:03 UTC, merged