feat: 최근 검색 기록 추가
swift-in-gangnam/soil pull request #57
Opened 2022-04-20 12:35 UTC by dudtjs1021ej

## Linked Issue

close #53

## 설명

UserDefault와 tableView를 사용하여 SearchController에 최근 검색 기록 구현했습니다.

## 변경 사항

__Modify__
- Soil.xcodeproj/project.pbxproj
- Soil/Controller/Search/SearchController.swift

__Add__
- Soil/Supporting/Assets.xcassets/Button Images/xButton.imageset/Contents.json
- Soil/View/SearchTableViewCell.swift
- Soil/Model/Search.swift

## 참고 사항

---

## Pull Request의 유형은 무엇인가요?

- [x] New Feature
- [ ] Bug Fix
- [ ] Refactoring
- [ ] Docs
- [ ] Other

## 체크리스트

- [x] Merge하는 브랜치가 올바른가?
- [x] 코딩컨벤션을 준수하는가?
- [x] PR과 관련없는 변경사항이 없는가?
- [x] 내 코드에 대한 자기 검토가 되었는가?

2022-04-28 14:09 UTC, z3rosmith approved these changes
수고하셨습니다! 몇가지 코멘트를 남겼는데 그냥 읽어주세요!

2022-04-28 14:09 UTC, z3rosmith commented on Soil/Controller/Search/SearchController.swift
> +    cell.selectionStyle = .none
cell의 backgroundColor와 selectionStyle은 SearchTableViewCell class의 init 부분에서 설정해줘도 될것같습니다 이건 절대적인건 아니고 그냥 의견사항입니다!

2022-04-28 14:09 UTC, z3rosmith commented on Soil/Controller/Search/SearchController.swift
> +      if searchBarText != "" {
if let searchBarText = searchBar.text, searchBarText.isEmty == false로 묶어줘도 좋을것같습니다

2022-05-03 15:11 UTC, dudtjs1021ej reviewed
@z3rosmith  의견 주셔서 감사합니다! 모두 수정 했습니당

2022-05-03 15:11 UTC, dudtjs1021ej commented on Soil/View/SearchTableViewCell.swift
> +    selectionStyle = .none
cell의 init에서 처리하는걸로 수정했어요👍

2022-05-03 15:11 UTC, dudtjs1021ej commented on Soil/Controller/Search/SearchController.swift
> +    if let searchBarText = searchBar.text, searchBarText.isEmpty == false {
이 부분도 수정완료! 가독성이 더 좋네요

2022-05-03 15:17 UTC, dudtjs1021ej commented
@z3rosmith  @Chuncheonian 
Search tableView를 DiffableDataSource로 구현하며 리팩토링 했습니다. 리뷰 부탁드려요!

2022-05-04 13:04 UTC, Chuncheonian requested changes
Diffable로 구현하시느라 고생많았습니다.👍

피드백은 코멘트로 남겨봤습니다!

2022-05-04 13:04 UTC, Chuncheonian commented on Soil/View/SearchTableViewCell.swift
> +  }
이 함수는 처음 보는데 어떨 때 쓰는건가요?🤔

2022-05-05 14:46 UTC, dudtjs1021ej commented on Soil/Model/Search.swift
> +}
맞아요 오류 떠서 var 로 바꿨었는데 이렇게 쓰면 되겠네요!

2022-05-05 14:57 UTC, dudtjs1021ej commented on Soil/View/SearchTableViewCell.swift
> +  }
찾아보니까 선택된 cell 관련 설정 해줄 때 쓰더라구요 (ex 선택된 cell에 borderColor를 넣는경우)
UITableViewCell 프로토콜 구현 메소드라서 
파일 생성하고 지우지 않고 놔두었는데 지우는 게 나을까요?

2022-05-06 14:44 UTC, Chuncheonian commented on Soil/Model/Search.swift
> +}
아 UserDefault에서 쓰는군요. 담부턴 더 꼼꼼히 보겠습니다.😱

2022-05-06 14:47 UTC, Chuncheonian commented on Soil/View/SearchTableViewCell.swift
> +  }
음.. 저기 안에 코드를 실행할 필요없고 없어도 오류가 안 뜨면 지워도 좋을 거 같습니다!

2022-05-08 14:34 UTC, dudtjs1021ej reviewed
@Chuncheonian 의견 주셔서 감사합니다! 모두 반영했습니다👍

2022-05-08 14:34 UTC, dudtjs1021ej commented on Soil/Model/Search.swift
> +  private(set) var uuid = UUID()
private(set)으로 변경했습니다.

2022-05-08 14:34 UTC, dudtjs1021ej commented on Soil/View/SearchRecentTableViewCell.swift
> +class SearchRecentTableViewCell: UITableViewCell {
SearchRecentTableViewCell로 rename했습니다.

2022-05-08 14:34 UTC, dudtjs1021ej commented on Soil/View/SearchRecentTableViewCell.swift
> +    backgroundColor = .soilBackgroundColor
.soilBackgroundColor로 수정했습니다.

2022-05-08 14:34 UTC, dudtjs1021ej commented on Soil/Controller/Search/SearchController.swift
> +   }
가독성을 위해 수정완료했습니다!

2022-05-09 06:29 UTC, Chuncheonian approved these changes

2022-05-09 10:11 UTC, merged